#!/bin/bash

# Description: Link dotfiles to home directory
JB_DOTFILES=$(pwd)

mkdir -p ~/.config

ln -sf $JB_DOTFILES/.bashrc ~/.bashrc
ln -sf $JB_DOTFILES/.vimrc ~/.vimrc
ln -sf $JB_DOTFILES/starship.toml ~/.config/starship.toml

echo "Dotfiles linked!"
